"""
Dataset estructurado con plantillas de referencia para los 25 clubes europeos de EA FC.
Utilizado como contingencia/enriquecimiento garantizado de estadísticas para el scraping.
"""

FALLBACK_SQUADS = {
    "Manchester City": [
        {"name": "Ederson", "position": "GK", "rating": 88, "pace": 64, "shooting": 60, "passing": 93, "dribbling": 87, "defending": 64, "physical": 78, "nationality": "Brasil"},
        {"name": "Rúben Dias", "position": "CB", "rating": 88, "pace": 66, "shooting": 39, "passing": 70, "dribbling": 68, "defending": 89, "physical": 87, "nationality": "Portugal"},
        {"name": "Josko Gvardiol", "position": "LB", "rating": 83, "pace": 78, "shooting": 64, "passing": 75, "dribbling": 78, "defending": 82, "physical": 84, "nationality": "Croacia"},
        {"name": "Manuel Akanji", "position": "CB", "rating": 83, "pace": 79, "shooting": 48, "passing": 72, "dribbling": 72, "defending": 84, "physical": 82, "nationality": "Suiza"},
        {"name": "Kyle Walker", "position": "RB", "rating": 84, "pace": 90, "shooting": 63, "passing": 76, "dribbling": 77, "defending": 81, "physical": 81, "nationality": "Inglaterra"},
        {"name": "Rodri", "position": "CDM", "rating": 91, "pace": 66, "shooting": 80, "passing": 86, "dribbling": 84, "defending": 87, "physical": 85, "nationality": "España"},
        {"name": "Kevin De Bruyne", "position": "CM", "rating": 90, "pace": 67, "shooting": 87, "passing": 94, "dribbling": 87, "defending": 65, "physical": 75, "nationality": "Bélgica"},
        {"name": "Bernardo Silva", "position": "CAM", "rating": 88, "pace": 69, "shooting": 78, "passing": 86, "dribbling": 92, "defending": 69, "physical": 74, "nationality": "Portugal"},
        {"name": "Phil Foden", "position": "RW", "rating": 88, "pace": 86, "shooting": 85, "passing": 87, "dribbling": 90, "defending": 58, "physical": 64, "nationality": "Inglaterra"},
        {"name": "Jack Grealish", "position": "LW", "rating": 84, "pace": 76, "shooting": 76, "passing": 84, "dribbling": 87, "defending": 53, "physical": 69, "nationality": "Inglaterra"},
        {"name": "Erling Haaland", "position": "ST", "rating": 91, "pace": 89, "shooting": 93, "passing": 70, "dribbling": 81, "defending": 45, "physical": 88, "nationality": "Noruega"}
    ],
    "Arsenal FC": [
        {"name": "David Raya", "position": "GK", "rating": 83, "pace": 58, "shooting": 45, "passing": 84, "dribbling": 80, "defending": 45, "physical": 76, "nationality": "España"},
        {"name": "William Saliba", "position": "CB", "rating": 87, "pace": 82, "shooting": 38, "passing": 72, "dribbling": 74, "defending": 87, "physical": 83, "nationality": "Francia"},
        {"name": "Gabriel Magalhães", "position": "CB", "rating": 86, "pace": 68, "shooting": 40, "passing": 66, "dribbling": 65, "defending": 86, "physical": 84, "nationality": "Brasil"},
        {"name": "Ben White", "position": "RB", "rating": 82, "pace": 74, "shooting": 42, "passing": 76, "dribbling": 77, "defending": 82, "physical": 76, "nationality": "Inglaterra"},
        {"name": "Oleksandr Zinchenko", "position": "LB", "rating": 79, "pace": 74, "shooting": 68, "passing": 82, "dribbling": 83, "defending": 76, "physical": 68, "nationality": "Ucrania"},
        {"name": "Declan Rice", "position": "CDM", "rating": 87, "pace": 74, "shooting": 70, "passing": 82, "dribbling": 80, "defending": 86, "physical": 86, "nationality": "Inglaterra"},
        {"name": "Martin Ødegaard", "position": "CAM", "rating": 89, "pace": 74, "shooting": 82, "passing": 89, "dribbling": 89, "defending": 66, "physical": 67, "nationality": "Noruega"},
        {"name": "Mikel Merino", "position": "CM", "rating": 83, "pace": 67, "shooting": 76, "passing": 80, "dribbling": 80, "defending": 81, "physical": 82, "nationality": "España"},
        {"name": "Bukayo Saka", "position": "RW", "rating": 87, "pace": 86, "shooting": 83, "passing": 83, "dribbling": 88, "defending": 65, "physical": 76, "nationality": "Inglaterra"},
        {"name": "Gabriel Martinelli", "position": "LW", "rating": 83, "pace": 89, "shooting": 79, "passing": 77, "dribbling": 86, "defending": 45, "physical": 72, "nationality": "Brasil"},
        {"name": "Kai Havertz", "position": "ST", "rating": 83, "pace": 80, "shooting": 80, "passing": 80, "dribbling": 83, "defending": 54, "physical": 76, "nationality": "Alemania"}
    ],
    "Liverpool FC": [
        {"name": "Alisson Becker", "position": "GK", "rating": 89, "pace": 56, "shooting": 45, "passing": 85, "dribbling": 86, "defending": 55, "physical": 78, "nationality": "Brasil"},
        {"name": "Virgil van Dijk", "position": "CB", "rating": 89, "pace": 78, "shooting": 60, "passing": 72, "dribbling": 72, "defending": 89, "physical": 86, "nationality": "Países Bajos"},
        {"name": "Ibrahima Konaté", "position": "CB", "rating": 83, "pace": 78, "shooting": 34, "passing": 58, "dribbling": 66, "defending": 83, "physical": 84, "nationality": "Francia"},
        {"name": "Trent Alexander-Arnold", "position": "RB", "rating": 86, "pace": 76, "shooting": 76, "passing": 90, "dribbling": 80, "defending": 79, "physical": 73, "nationality": "Inglaterra"},
        {"name": "Andrew Robertson", "position": "LB", "rating": 85, "pace": 80, "shooting": 61, "passing": 81, "dribbling": 80, "defending": 81, "physical": 76, "nationality": "Escocia"},
        {"name": "Alexis Mac Allister", "position": "CM", "rating": 86, "pace": 70, "shooting": 80, "passing": 86, "dribbling": 85, "defending": 78, "physical": 77, "nationality": "Argentina"},
        {"name": "Dominik Szoboszlai", "position": "CAM", "rating": 83, "pace": 82, "shooting": 82, "passing": 84, "dribbling": 83, "defending": 64, "physical": 77, "nationality": "Hungría"},
        {"name": "Ryan Gravenberch", "position": "CM", "rating": 80, "pace": 78, "shooting": 72, "passing": 79, "dribbling": 83, "defending": 72, "physical": 77, "nationality": "Países Bajos"},
        {"name": "Mohamed Salah", "position": "RW", "rating": 89, "pace": 89, "shooting": 87, "passing": 82, "dribbling": 88, "defending": 45, "physical": 76, "nationality": "Egipto"},
        {"name": "Luis Díaz", "position": "LW", "rating": 84, "pace": 90, "shooting": 80, "passing": 76, "dribbling": 87, "defending": 42, "physical": 73, "nationality": "Colombia"},
        {"name": "Darwin Núñez", "position": "ST", "rating": 82, "pace": 90, "shooting": 81, "passing": 71, "dribbling": 77, "defending": 42, "physical": 86, "nationality": "Uruguay"}
    ],
    "Manchester United": [
        {"name": "André Onana", "position": "GK", "rating": 83, "pace": 54, "shooting": 42, "passing": 84, "dribbling": 82, "defending": 48, "physical": 77, "nationality": "Camerún"},
        {"name": "Matthijs de Ligt", "position": "CB", "rating": 84, "pace": 70, "shooting": 58, "passing": 68, "dribbling": 68, "defending": 84, "physical": 85, "nationality": "Países Bajos"},
        {"name": "Lisandro Martínez", "position": "CB", "rating": 84, "pace": 73, "shooting": 58, "passing": 80, "dribbling": 78, "defending": 84, "physical": 80, "nationality": "Argentina"},
        {"name": "Diogo Dalot", "position": "RB", "rating": 82, "pace": 82, "shooting": 70, "passing": 78, "dribbling": 80, "defending": 78, "physical": 78, "nationality": "Portugal"},
        {"name": "Luke Shaw", "position": "LB", "rating": 81, "pace": 76, "shooting": 60, "passing": 78, "dribbling": 80, "defending": 80, "physical": 78, "nationality": "Inglaterra"},
        {"name": "Casemiro", "position": "CDM", "rating": 84, "pace": 58, "shooting": 72, "passing": 75, "dribbling": 72, "defending": 85, "physical": 84, "nationality": "Brasil"},
        {"name": "Kobbie Mainoo", "position": "CM", "rating": 79, "pace": 74, "shooting": 70, "passing": 79, "dribbling": 83, "defending": 75, "physical": 74, "nationality": "Inglaterra"},
        {"name": "Bruno Fernandes", "position": "CAM", "rating": 87, "pace": 71, "shooting": 85, "passing": 89, "dribbling": 83, "defending": 68, "physical": 76, "nationality": "Portugal"},
        {"name": "Alejandro Garnacho", "position": "RW", "rating": 80, "pace": 88, "shooting": 76, "passing": 74, "dribbling": 82, "defending": 38, "physical": 63, "nationality": "Argentina"},
        {"name": "Marcus Rashford", "position": "LW", "rating": 81, "pace": 89, "shooting": 82, "passing": 77, "dribbling": 82, "defending": 42, "physical": 74, "nationality": "Inglaterra"},
        {"name": "Rasmus Højlund", "position": "ST", "rating": 79, "pace": 86, "shooting": 78, "passing": 65, "dribbling": 76, "defending": 36, "physical": 80, "nationality": "Dinamarca"}
    ],
    "Chelsea FC": [
        {"name": "Robert Sánchez", "position": "GK", "rating": 78, "pace": 52, "shooting": 40, "passing": 75, "dribbling": 76, "defending": 45, "physical": 75, "nationality": "España"},
        {"name": "Levi Colwill", "position": "CB", "rating": 79, "pace": 72, "shooting": 40, "passing": 71, "dribbling": 72, "defending": 80, "physical": 78, "nationality": "Inglaterra"},
        {"name": "Wesley Fofana", "position": "CB", "rating": 79, "pace": 76, "shooting": 42, "passing": 65, "dribbling": 68, "defending": 80, "physical": 77, "nationality": "Francia"},
        {"name": "Reece James", "position": "RB", "rating": 83, "pace": 80, "shooting": 73, "passing": 82, "dribbling": 82, "defending": 81, "physical": 82, "nationality": "Inglaterra"},
        {"name": "Marc Cucurella", "position": "LB", "rating": 81, "pace": 78, "shooting": 62, "passing": 77, "dribbling": 78, "defending": 79, "physical": 78, "nationality": "España"},
        {"name": "Moisés Caicedo", "position": "CDM", "rating": 83, "pace": 74, "shooting": 65, "passing": 78, "dribbling": 79, "defending": 82, "physical": 82, "nationality": "Ecuador"},
        {"name": "Enzo Fernández", "position": "CM", "rating": 82, "pace": 68, "shooting": 76, "passing": 84, "dribbling": 82, "defending": 76, "physical": 77, "nationality": "Argentina"},
        {"name": "Cole Palmer", "position": "CAM", "rating": 85, "pace": 80, "shooting": 83, "passing": 85, "dribbling": 86, "defending": 54, "physical": 68, "nationality": "Inglaterra"},
        {"name": "Noni Madueke", "position": "RW", "rating": 78, "pace": 87, "shooting": 74, "passing": 73, "dribbling": 82, "defending": 38, "physical": 68, "nationality": "Inglaterra"},
        {"name": "Pedro Neto", "position": "LW", "rating": 80, "pace": 88, "shooting": 75, "passing": 77, "dribbling": 84, "defending": 39, "physical": 66, "nationality": "Portugal"},
        {"name": "Nicolas Jackson", "position": "ST", "rating": 80, "pace": 85, "shooting": 77, "passing": 68, "dribbling": 78, "defending": 38, "physical": 76, "nationality": "Senegal"}
    ],
    "Real Madrid": [
        {"name": "Thibaut Courtois", "position": "GK", "rating": 89, "pace": 52, "shooting": 48, "passing": 74, "dribbling": 72, "defending": 50, "physical": 77, "nationality": "Bélgica"},
        {"name": "Éder Militão", "position": "CB", "rating": 85, "pace": 84, "shooting": 50, "passing": 70, "dribbling": 72, "defending": 85, "physical": 82, "nationality": "Brasil"},
        {"name": "Antonio Rüdiger", "position": "CB", "rating": 87, "pace": 82, "shooting": 54, "passing": 71, "dribbling": 68, "defending": 86, "physical": 86, "nationality": "Alemania"},
        {"name": "Dani Carvajal", "position": "RB", "rating": 85, "pace": 80, "shooting": 60, "passing": 80, "dribbling": 81, "defending": 82, "physical": 80, "nationality": "España"},
        {"name": "Ferland Mendy", "position": "LB", "rating": 82, "pace": 89, "shooting": 62, "passing": 74, "dribbling": 78, "defending": 81, "physical": 84, "nationality": "Francia"},
        {"name": "Aurélien Tchouaméni", "position": "CDM", "rating": 85, "pace": 75, "shooting": 74, "passing": 81, "dribbling": 80, "defending": 83, "physical": 84, "nationality": "Francia"},
        {"name": "Federico Valverde", "position": "CM", "rating": 88, "pace": 88, "shooting": 84, "passing": 84, "dribbling": 83, "defending": 81, "physical": 85, "nationality": "Uruguay"},
        {"name": "Jude Bellingham", "position": "CAM", "rating": 90, "pace": 80, "shooting": 87, "passing": 84, "dribbling": 88, "defending": 79, "physical": 84, "nationality": "Inglaterra"},
        {"name": "Rodrygo", "position": "RW", "rating": 86, "pace": 89, "shooting": 82, "passing": 81, "dribbling": 87, "defending": 53, "physical": 64, "nationality": "Brasil"},
        {"name": "Vinicius Jr", "position": "LW", "rating": 90, "pace": 95, "shooting": 84, "passing": 81, "dribbling": 91, "defending": 39, "physical": 69, "nationality": "Brasil"},
        {"name": "Kylian Mbappé", "position": "ST", "rating": 91, "pace": 97, "shooting": 90, "passing": 80, "dribbling": 92, "defending": 36, "physical": 78, "nationality": "Francia"}
    ],
    "FC Barcelona": [
        {"name": "Marc-André ter Stegen", "position": "GK", "rating": 89, "pace": 54, "shooting": 46, "passing": 87, "dribbling": 85, "defending": 48, "physical": 78, "nationality": "Alemania"},
        {"name": "Ronald Araújo", "position": "CB", "rating": 85, "pace": 83, "shooting": 48, "passing": 65, "dribbling": 65, "defending": 85, "physical": 84, "nationality": "Uruguay"},
        {"name": "Pau Cubarsí", "position": "CB", "rating": 80, "pace": 72, "shooting": 40, "passing": 78, "dribbling": 75, "defending": 81, "physical": 74, "nationality": "España"},
        {"name": "Jules Koundé", "position": "RB", "rating": 85, "pace": 84, "shooting": 45, "passing": 75, "dribbling": 77, "defending": 85, "physical": 78, "nationality": "Francia"},
        {"name": "Alejandro Balde", "position": "LB", "rating": 81, "pace": 91, "shooting": 50, "passing": 73, "dribbling": 79, "defending": 76, "physical": 68, "nationality": "España"},
        {"name": "Marc Casadó", "position": "CDM", "rating": 78, "pace": 72, "shooting": 62, "passing": 78, "dribbling": 77, "defending": 77, "physical": 75, "nationality": "España"},
        {"name": "Pedri", "position": "CM", "rating": 86, "pace": 78, "shooting": 72, "passing": 86, "dribbling": 89, "defending": 70, "physical": 68, "nationality": "España"},
        {"name": "Dani Olmo", "position": "CAM", "rating": 84, "pace": 78, "shooting": 81, "passing": 83, "dribbling": 86, "defending": 54, "physical": 66, "nationality": "España"},
        {"name": "Lamine Yamal", "position": "RW", "rating": 84, "pace": 87, "shooting": 80, "passing": 82, "dribbling": 88, "defending": 42, "physical": 58, "nationality": "España"},
        {"name": "Raphinha", "position": "LW", "rating": 85, "pace": 89, "shooting": 82, "passing": 81, "dribbling": 86, "defending": 55, "physical": 73, "nationality": "Brasil"},
        {"name": "Robert Lewandowski", "position": "ST", "rating": 88, "pace": 74, "shooting": 88, "passing": 79, "dribbling": 85, "defending": 44, "physical": 80, "nationality": "Polonia"}
    ],
    "Atlético de Madrid": [
        {"name": "Jan Oblak", "position": "GK", "rating": 88, "pace": 50, "shooting": 44, "passing": 76, "dribbling": 78, "defending": 48, "physical": 80, "nationality": "Eslovenia"},
        {"name": "Robin Le Normand", "position": "CB", "rating": 83, "pace": 70, "shooting": 40, "passing": 68, "dribbling": 68, "defending": 84, "physical": 82, "nationality": "España"},
        {"name": "José María Giménez", "position": "CB", "rating": 83, "pace": 72, "shooting": 45, "passing": 60, "dribbling": 62, "defending": 84, "physical": 83, "nationality": "Uruguay"},
        {"name": "Nahuel Molina", "position": "RB", "rating": 81, "pace": 84, "shooting": 68, "passing": 76, "dribbling": 78, "defending": 76, "physical": 75, "nationality": "Argentina"},
        {"name": "Reinildo Mandava", "position": "LB", "rating": 80, "pace": 80, "shooting": 55, "passing": 68, "dribbling": 72, "defending": 81, "physical": 80, "nationality": "Mozambique"},
        {"name": "Koke", "position": "CM", "rating": 82, "pace": 64, "shooting": 72, "passing": 83, "dribbling": 80, "defending": 78, "physical": 77, "nationality": "España"},
        {"name": "Rodrigo De Paul", "position": "CM", "rating": 84, "pace": 76, "shooting": 77, "passing": 83, "dribbling": 82, "defending": 78, "physical": 82, "nationality": "Argentina"},
        {"name": "Conor Gallagher", "position": "CM", "rating": 81, "pace": 77, "shooting": 76, "passing": 78, "dribbling": 79, "defending": 77, "physical": 82, "nationality": "Inglaterra"},
        {"name": "Antoine Griezmann", "position": "CAM", "rating": 88, "pace": 80, "shooting": 88, "passing": 87, "dribbling": 88, "defending": 72, "physical": 74, "nationality": "Francia"},
        {"name": "Julián Álvarez", "position": "ST", "rating": 84, "pace": 84, "shooting": 83, "passing": 79, "dribbling": 84, "defending": 58, "physical": 77, "nationality": "Argentina"},
        {"name": "Alexander Sørloth", "position": "ST", "rating": 82, "pace": 82, "shooting": 83, "passing": 72, "dribbling": 77, "defending": 40, "physical": 86, "nationality": "Noruega"}
    ],
    "Girona FC": [
        {"name": "Paulo Gazzaniga", "position": "GK", "rating": 78, "pace": 50, "shooting": 40, "passing": 72, "dribbling": 72, "defending": 45, "physical": 74, "nationality": "Argentina"},
        {"name": "David López", "position": "CB", "rating": 78, "pace": 62, "shooting": 55, "passing": 72, "dribbling": 70, "defending": 79, "physical": 76, "nationality": "España"},
        {"name": "Daley Blind", "position": "CB", "rating": 78, "pace": 58, "shooting": 65, "passing": 82, "dribbling": 76, "defending": 79, "physical": 72, "nationality": "Países Bajos"},
        {"name": "Arnau Martínez", "position": "RB", "rating": 77, "pace": 75, "shooting": 60, "passing": 74, "dribbling": 76, "defending": 76, "physical": 74, "nationality": "España"},
        {"name": "Miguel Gutiérrez", "position": "LB", "rating": 79, "pace": 82, "shooting": 66, "passing": 78, "dribbling": 80, "defending": 74, "physical": 70, "nationality": "España"},
        {"name": "Yangel Herrera", "position": "CDM", "rating": 79, "pace": 74, "shooting": 74, "passing": 76, "dribbling": 77, "defending": 78, "physical": 82, "nationality": "Venezuela"},
        {"name": "Iván Martín", "position": "CM", "rating": 78, "pace": 74, "shooting": 72, "passing": 79, "dribbling": 80, "defending": 68, "physical": 68, "nationality": "España"},
        {"name": "Viktor Tsygankov", "position": "RW", "rating": 81, "pace": 82, "shooting": 79, "passing": 80, "dribbling": 83, "defending": 48, "physical": 68, "nationality": "Ucrania"},
        {"name": "Bryan Gil", "position": "LW", "rating": 77, "pace": 84, "shooting": 70, "passing": 75, "dribbling": 82, "defending": 42, "physical": 60, "nationality": "España"},
        {"name": "Abel Ruiz", "position": "ST", "rating": 76, "pace": 76, "shooting": 76, "passing": 70, "dribbling": 76, "defending": 38, "physical": 74, "nationality": "España"},
        {"name": "Bojan Miovski", "position": "ST", "rating": 76, "pace": 77, "shooting": 77, "passing": 64, "dribbling": 73, "defending": 35, "physical": 76, "nationality": "Macedonia del Norte"}
    ],
    "Athletic Club": [
        {"name": "Unai Simón", "position": "GK", "rating": 85, "pace": 52, "shooting": 45, "passing": 78, "dribbling": 79, "defending": 48, "physical": 78, "nationality": "España"},
        {"name": "Dani Vivian", "position": "CB", "rating": 81, "pace": 77, "shooting": 38, "passing": 64, "dribbling": 65, "defending": 82, "physical": 82, "nationality": "España"},
        {"name": "Aitor Paredes", "position": "CB", "rating": 78, "pace": 72, "shooting": 36, "passing": 62, "dribbling": 64, "defending": 79, "physical": 79, "nationality": "España"},
        {"name": "Óscar de Marcos", "position": "RB", "rating": 78, "pace": 76, "shooting": 68, "passing": 75, "dribbling": 76, "defending": 76, "physical": 75, "nationality": "España"},
        {"name": "Yuri Berchiche", "position": "LB", "rating": 79, "pace": 78, "shooting": 70, "passing": 75, "dribbling": 76, "defending": 78, "physical": 80, "nationality": "España"},
        {"name": "Mikel Vesga", "position": "CDM", "rating": 77, "pace": 62, "shooting": 68, "passing": 76, "dribbling": 72, "defending": 77, "physical": 80, "nationality": "España"},
        {"name": "Iñigo Ruiz de Galarreta", "position": "CM", "rating": 78, "pace": 68, "shooting": 67, "passing": 80, "dribbling": 78, "defending": 75, "physical": 70, "nationality": "España"},
        {"name": "Oihan Sancet", "position": "CAM", "rating": 81, "pace": 74, "shooting": 80, "passing": 79, "dribbling": 82, "defending": 64, "physical": 78, "nationality": "España"},
        {"name": "Nico Williams", "position": "LW", "rating": 85, "pace": 93, "shooting": 79, "passing": 80, "dribbling": 86, "defending": 42, "physical": 68, "nationality": "España"},
        {"name": "Iñaki Williams", "position": "RW", "rating": 82, "pace": 91, "shooting": 79, "passing": 74, "dribbling": 80, "defending": 45, "physical": 81, "nationality": "Ghana"},
        {"name": "Gorka Guruzeta", "position": "ST", "rating": 79, "pace": 76, "shooting": 80, "passing": 72, "dribbling": 76, "defending": 40, "physical": 74, "nationality": "España"}
    ],
    "Inter de Milán": [
        {"name": "Yann Sommer", "position": "GK", "rating": 87, "pace": 50, "shooting": 44, "passing": 82, "dribbling": 83, "defending": 50, "physical": 74, "nationality": "Suiza"},
        {"name": "Alessandro Bastoni", "position": "CB", "rating": 87, "pace": 75, "shooting": 48, "passing": 80, "dribbling": 78, "defending": 87, "physical": 83, "nationality": "Italia"},
        {"name": "Benjamin Pavard", "position": "CB", "rating": 84, "pace": 74, "shooting": 66, "passing": 76, "dribbling": 76, "defending": 84, "physical": 79, "nationality": "Francia"},
        {"name": "Stefan de Vrij", "position": "CB", "rating": 82, "pace": 60, "shooting": 45, "passing": 68, "dribbling": 68, "defending": 83, "physical": 78, "nationality": "Países Bajos"},
        {"name": "Denzel Dumfries", "position": "RB", "rating": 82, "pace": 84, "shooting": 68, "passing": 73, "dribbling": 76, "defending": 78, "physical": 86, "nationality": "Países Bajos"},
        {"name": "Federico Dimarco", "position": "LB", "rating": 84, "pace": 82, "shooting": 76, "passing": 85, "dribbling": 82, "defending": 78, "physical": 74, "nationality": "Italia"},
        {"name": "Hakan Çalhanoğlu", "position": "CDM", "rating": 86, "pace": 68, "shooting": 84, "passing": 88, "dribbling": 84, "defending": 76, "physical": 73, "nationality": "Turquía"},
        {"name": "Nicolò Barella", "position": "CM", "rating": 87, "pace": 78, "shooting": 78, "passing": 84, "dribbling": 86, "defending": 80, "physical": 82, "nationality": "Italia"},
        {"name": "Henrikh Mkhitaryan", "position": "CM", "rating": 83, "pace": 74, "shooting": 78, "passing": 82, "dribbling": 83, "defending": 68, "physical": 68, "nationality": "Armenia"},
        {"name": "Marcus Thuram", "position": "ST", "rating": 84, "pace": 87, "shooting": 82, "passing": 76, "dribbling": 82, "defending": 48, "physical": 82, "nationality": "Francia"},
        {"name": "Lautaro Martínez", "position": "ST", "rating": 89, "pace": 82, "shooting": 88, "passing": 77, "dribbling": 86, "defending": 48, "physical": 84, "nationality": "Argentina"}
    ],
    "AC Milan": [
        {"name": "Mike Maignan", "position": "GK", "rating": 87, "pace": 52, "shooting": 45, "passing": 83, "dribbling": 85, "defending": 50, "physical": 80, "nationality": "Francia"},
        {"name": "Fikayo Tomori", "position": "CB", "rating": 83, "pace": 84, "shooting": 40, "passing": 64, "dribbling": 68, "defending": 84, "physical": 80, "nationality": "Inglaterra"},
        {"name": "Strahinja Pavlović", "position": "CB", "rating": 79, "pace": 76, "shooting": 44, "passing": 62, "dribbling": 65, "defending": 80, "physical": 85, "nationality": "Serbia"},
        {"name": "Davide Calabria", "position": "RB", "rating": 79, "pace": 78, "shooting": 58, "passing": 75, "dribbling": 77, "defending": 79, "physical": 74, "nationality": "Italia"},
        {"name": "Theo Hernández", "position": "LB", "rating": 87, "pace": 93, "shooting": 76, "passing": 80, "dribbling": 84, "defending": 80, "physical": 86, "nationality": "Francia"},
        {"name": "Tijjani Reijnders", "position": "CM", "rating": 82, "pace": 76, "shooting": 76, "passing": 81, "dribbling": 84, "defending": 74, "physical": 76, "nationality": "Países Bajos"},
        {"name": "Youssouf Fofana", "position": "CDM", "rating": 81, "pace": 75, "shooting": 72, "passing": 78, "dribbling": 79, "defending": 80, "physical": 84, "nationality": "Francia"},
        {"name": "Ruben Loftus-Cheek", "position": "CAM", "rating": 80, "pace": 76, "shooting": 77, "passing": 77, "dribbling": 82, "defending": 72, "physical": 82, "nationality": "Inglaterra"},
        {"name": "Christian Pulisic", "position": "RW", "rating": 83, "pace": 88, "shooting": 80, "passing": 79, "dribbling": 86, "defending": 42, "physical": 65, "nationality": "Estados Unidos"},
        {"name": "Rafael Leão", "position": "LW", "rating": 86, "pace": 93, "shooting": 81, "passing": 78, "dribbling": 88, "defending": 32, "physical": 76, "nationality": "Portugal"},
        {"name": "Álvaro Morata", "position": "ST", "rating": 83, "pace": 80, "shooting": 83, "passing": 74, "dribbling": 79, "defending": 42, "physical": 78, "nationality": "España"}
    ],
    "Juventus FC": [
        {"name": "Michele Di Gregorio", "position": "GK", "rating": 82, "pace": 50, "shooting": 42, "passing": 77, "dribbling": 80, "defending": 46, "physical": 76, "nationality": "Italia"},
        {"name": "Bremer", "position": "CB", "rating": 86, "pace": 80, "shooting": 50, "passing": 62, "dribbling": 66, "defending": 87, "physical": 86, "nationality": "Brasil"},
        {"name": "Federico Gatti", "position": "CB", "rating": 79, "pace": 72, "shooting": 48, "passing": 62, "dribbling": 64, "defending": 80, "physical": 83, "nationality": "Italia"},
        {"name": "Pierre Kalulu", "position": "RB", "rating": 78, "pace": 81, "shooting": 44, "passing": 68, "dribbling": 72, "defending": 79, "physical": 78, "nationality": "Francia"},
        {"name": "Andrea Cambiaso", "position": "LB", "rating": 80, "pace": 81, "shooting": 68, "passing": 78, "dribbling": 80, "defending": 76, "physical": 74, "nationality": "Italia"},
        {"name": "Manuel Locatelli", "position": "CDM", "rating": 82, "pace": 68, "shooting": 72, "passing": 82, "dribbling": 79, "defending": 80, "physical": 79, "nationality": "Italia"},
        {"name": "Teun Koopmeiners", "position": "CM", "rating": 83, "pace": 74, "shooting": 82, "passing": 83, "dribbling": 80, "defending": 76, "physical": 80, "nationality": "Países Bajos"},
        {"name": "Douglas Luiz", "position": "CM", "rating": 83, "pace": 72, "shooting": 78, "passing": 82, "dribbling": 82, "defending": 78, "physical": 79, "nationality": "Brasil"},
        {"name": "Nicolás González", "position": "RW", "rating": 80, "pace": 82, "shooting": 78, "passing": 76, "dribbling": 82, "defending": 54, "physical": 76, "nationality": "Argentina"},
        {"name": "Kenan Yildiz", "position": "LW", "rating": 78, "pace": 84, "shooting": 76, "passing": 75, "dribbling": 83, "defending": 40, "physical": 68, "nationality": "Turquía"},
        {"name": "Dušan Vlahović", "position": "ST", "rating": 84, "pace": 81, "shooting": 86, "passing": 68, "dribbling": 78, "defending": 36, "physical": 83, "nationality": "Serbia"}
    ],
    "AS Roma": [
        {"name": "Mile Svilar", "position": "GK", "rating": 80, "pace": 50, "shooting": 40, "passing": 75, "dribbling": 77, "defending": 46, "physical": 74, "nationality": "Serbia"},
        {"name": "Gianluca Mancini", "position": "CB", "rating": 81, "pace": 68, "shooting": 54, "passing": 66, "dribbling": 68, "defending": 82, "physical": 84, "nationality": "Italia"},
        {"name": "Evan Ndicka", "position": "CB", "rating": 80, "pace": 74, "shooting": 44, "passing": 68, "dribbling": 69, "defending": 81, "physical": 82, "nationality": "Costa de Marfil"},
        {"name": "Zeki Çelik", "position": "RB", "rating": 76, "pace": 77, "shooting": 56, "passing": 70, "dribbling": 74, "defending": 76, "physical": 76, "nationality": "Turquía"},
        {"name": "Angeliño", "position": "LB", "rating": 79, "pace": 79, "shooting": 72, "passing": 80, "dribbling": 81, "defending": 74, "physical": 68, "nationality": "España"},
        {"name": "Bryan Cristante", "position": "CDM", "rating": 80, "pace": 60, "shooting": 74, "passing": 79, "dribbling": 74, "defending": 80, "physical": 82, "nationality": "Italia"},
        {"name": "Lorenzo Pellegrini", "position": "CAM", "rating": 82, "pace": 75, "shooting": 79, "passing": 83, "dribbling": 82, "defending": 70, "physical": 74, "nationality": "Italia"},
        {"name": "Manu Koné", "position": "CM", "rating": 78, "pace": 76, "shooting": 68, "passing": 76, "dribbling": 82, "defending": 76, "physical": 80, "nationality": "Francia"},
        {"name": "Paulo Dybala", "position": "RW", "rating": 86, "pace": 80, "shooting": 86, "passing": 86, "dribbling": 89, "defending": 40, "physical": 62, "nationality": "Argentina"},
        {"name": "Stephan El Shaarawy", "position": "LW", "rating": 78, "pace": 82, "shooting": 77, "passing": 76, "dribbling": 81, "defending": 52, "physical": 66, "nationality": "Italia"},
        {"name": "Artem Dovbyk", "position": "ST", "rating": 84, "pace": 82, "shooting": 84, "passing": 68, "dribbling": 76, "defending": 38, "physical": 84, "nationality": "Ucrania"}
    ],
    "SSC Napoli": [
        {"name": "Alex Meret", "position": "GK", "rating": 80, "pace": 50, "shooting": 40, "passing": 75, "dribbling": 78, "defending": 45, "physical": 74, "nationality": "Italia"},
        {"name": "Alessandro Buongiorno", "position": "CB", "rating": 82, "pace": 74, "shooting": 42, "passing": 68, "dribbling": 68, "defending": 83, "physical": 83, "nationality": "Italia"},
        {"name": "Amir Rrahmani", "position": "CB", "rating": 80, "pace": 68, "shooting": 48, "passing": 65, "dribbling": 65, "defending": 81, "physical": 80, "nationality": "Kosovo"},
        {"name": "Giovanni Di Lorenzo", "position": "RB", "rating": 82, "pace": 80, "shooting": 66, "passing": 78, "dribbling": 79, "defending": 81, "physical": 81, "nationality": "Italia"},
        {"name": "Mathías Olivera", "position": "LB", "rating": 78, "pace": 79, "shooting": 58, "passing": 72, "dribbling": 75, "defending": 78, "physical": 79, "nationality": "Uruguay"},
        {"name": "Stanislav Lobotka", "position": "CDM", "rating": 83, "pace": 72, "shooting": 66, "passing": 82, "dribbling": 85, "defending": 79, "physical": 77, "nationality": "Eslovaquia"},
        {"name": "André-Frank Zambo Anguissa", "position": "CM", "rating": 82, "pace": 75, "shooting": 71, "passing": 78, "dribbling": 82, "defending": 80, "physical": 84, "nationality": "Camerún"},
        {"name": "Scott McTominay", "position": "CM", "rating": 80, "pace": 74, "shooting": 78, "passing": 77, "dribbling": 78, "defending": 78, "physical": 84, "nationality": "Escocia"},
        {"name": "Matteo Politano", "position": "RW", "rating": 81, "pace": 82, "shooting": 78, "passing": 79, "dribbling": 83, "defending": 46, "physical": 65, "nationality": "Italia"},
        {"name": "Khvicha Kvaratskhelia", "position": "LW", "rating": 85, "pace": 86, "shooting": 82, "passing": 81, "dribbling": 88, "defending": 44, "physical": 75, "nationality": "Georgia"},
        {"name": "Romelu Lukaku", "position": "ST", "rating": 82, "pace": 78, "shooting": 83, "passing": 73, "dribbling": 76, "defending": 38, "physical": 85, "nationality": "Bélgica"}
    ],
    "Bayer 04 Leverkusen": [
        {"name": "Lukáš Hrádecký", "position": "GK", "rating": 83, "pace": 50, "shooting": 42, "passing": 75, "dribbling": 78, "defending": 46, "physical": 76, "nationality": "Finlandia"},
        {"name": "Jonathan Tah", "position": "CB", "rating": 86, "pace": 76, "shooting": 42, "passing": 68, "dribbling": 68, "defending": 86, "physical": 85, "nationality": "Alemania"},
        {"name": "Edmond Tapsoba", "position": "CB", "rating": 83, "pace": 78, "shooting": 56, "passing": 74, "dribbling": 75, "defending": 83, "physical": 82, "nationality": "Burkina Faso"},
        {"name": "Jeremie Frimpong", "position": "RB", "rating": 84, "pace": 95, "shooting": 76, "passing": 79, "dribbling": 86, "defending": 74, "physical": 72, "nationality": "Países Bajos"},
        {"name": "Alejandro Grimaldo", "position": "LB", "rating": 86, "pace": 84, "shooting": 82, "passing": 87, "dribbling": 84, "defending": 78, "physical": 74, "nationality": "España"},
        {"name": "Granit Xhaka", "position": "CDM", "rating": 86, "pace": 52, "shooting": 80, "passing": 88, "dribbling": 78, "defending": 82, "physical": 83, "nationality": "Suiza"},
        {"name": "Exequiel Palacios", "position": "CM", "rating": 84, "pace": 74, "shooting": 76, "passing": 83, "dribbling": 83, "defending": 82, "physical": 80, "nationality": "Argentina"},
        {"name": "Florian Wirtz", "position": "CAM", "rating": 88, "pace": 82, "shooting": 82, "passing": 87, "dribbling": 90, "defending": 55, "physical": 70, "nationality": "Alemania"},
        {"name": "Amine Adli", "position": "RW", "rating": 79, "pace": 86, "shooting": 75, "passing": 75, "dribbling": 82, "defending": 48, "physical": 70, "nationality": "Marruecos"},
        {"name": "Martin Terrier", "position": "LW", "rating": 80, "pace": 80, "shooting": 80, "passing": 76, "dribbling": 80, "defending": 45, "physical": 74, "nationality": "Francia"},
        {"name": "Victor Boniface", "position": "ST", "rating": 82, "pace": 82, "shooting": 82, "passing": 72, "dribbling": 82, "defending": 36, "physical": 86, "nationality": "Nigeria"}
    ],
    "Bayern Múnich": [
        {"name": "Manuel Neuer", "position": "GK", "rating": 88, "pace": 52, "shooting": 48, "passing": 88, "dribbling": 86, "defending": 54, "physical": 80, "nationality": "Alemania"},
        {"name": "Dayot Upamecano", "position": "CB", "rating": 83, "pace": 82, "shooting": 44, "passing": 68, "dribbling": 70, "defending": 83, "physical": 84, "nationality": "Francia"},
        {"name": "Kim Min-jae", "position": "CB", "rating": 83, "pace": 78, "shooting": 38, "passing": 66, "dribbling": 68, "defending": 84, "physical": 84, "nationality": "Corea del Sur"},
        {"name": "Alphonso Davies", "position": "LB", "rating": 82, "pace": 95, "shooting": 68, "passing": 77, "dribbling": 84, "defending": 76, "physical": 77, "nationality": "Canadá"},
        {"name": "Joshua Kimmich", "position": "RB", "rating": 86, "pace": 68, "shooting": 72, "passing": 88, "dribbling": 84, "defending": 82, "physical": 78, "nationality": "Alemania"},
        {"name": "João Palhinha", "position": "CDM", "rating": 85, "pace": 62, "shooting": 66, "passing": 74, "dribbling": 74, "defending": 86, "physical": 87, "nationality": "Portugal"},
        {"name": "Aleksandar Pavlović", "position": "CM", "rating": 78, "pace": 70, "shooting": 66, "passing": 80, "dribbling": 78, "defending": 76, "physical": 74, "nationality": "Alemania"},
        {"name": "Jamal Musiala", "position": "CAM", "rating": 87, "pace": 85, "shooting": 81, "passing": 82, "dribbling": 91, "defending": 64, "physical": 68, "nationality": "Alemania"},
        {"name": "Michael Olise", "position": "RW", "rating": 82, "pace": 82, "shooting": 78, "passing": 82, "dribbling": 86, "defending": 52, "physical": 68, "nationality": "Francia"},
        {"name": "Leroy Sané", "position": "LW", "rating": 84, "pace": 89, "shooting": 82, "passing": 80, "dribbling": 86, "defending": 38, "physical": 68, "nationality": "Alemania"},
        {"name": "Harry Kane", "position": "ST", "rating": 90, "pace": 68, "shooting": 93, "passing": 84, "dribbling": 83, "defending": 48, "physical": 82, "nationality": "Inglaterra"}
    ],
    "Borussia Dortmund": [
        {"name": "Gregor Kobel", "position": "GK", "rating": 88, "pace": 50, "shooting": 44, "passing": 76, "dribbling": 78, "defending": 48, "physical": 76, "nationality": "Suiza"},
        {"name": "Nico Schlotterbeck", "position": "CB", "rating": 85, "pace": 78, "shooting": 60, "passing": 75, "dribbling": 74, "defending": 85, "physical": 84, "nationality": "Alemania"},
        {"name": "Waldemar Anton", "position": "CB", "rating": 81, "pace": 72, "shooting": 46, "passing": 68, "dribbling": 68, "defending": 82, "physical": 82, "nationality": "Alemania"},
        {"name": "Yan Couto", "position": "RB", "rating": 78, "pace": 84, "shooting": 62, "passing": 76, "dribbling": 80, "defending": 72, "physical": 66, "nationality": "Brasil"},
        {"name": "Ramy Bensebaini", "position": "LB", "rating": 79, "pace": 75, "shooting": 73, "passing": 75, "dribbling": 76, "defending": 79, "physical": 80, "nationality": "Argelia"},
        {"name": "Emre Can", "position": "CDM", "rating": 81, "pace": 74, "shooting": 76, "passing": 78, "dribbling": 78, "defending": 82, "physical": 86, "nationality": "Alemania"},
        {"name": "Marcel Sabitzer", "position": "CM", "rating": 82, "pace": 75, "shooting": 81, "passing": 81, "dribbling": 80, "defending": 76, "physical": 79, "nationality": "Austria"},
        {"name": "Julian Brandt", "position": "CAM", "rating": 84, "pace": 78, "shooting": 80, "passing": 85, "dribbling": 86, "defending": 58, "physical": 68, "nationality": "Alemania"},
        {"name": "Donyell Malen", "position": "RW", "rating": 81, "pace": 88, "shooting": 81, "passing": 76, "dribbling": 83, "defending": 40, "physical": 74, "nationality": "Países Bajos"},
        {"name": "Jamie Gittens", "position": "LW", "rating": 77, "pace": 89, "shooting": 72, "passing": 71, "dribbling": 83, "defending": 36, "physical": 62, "nationality": "Inglaterra"},
        {"name": "Serhou Guirassy", "position": "ST", "rating": 83, "pace": 80, "shooting": 84, "passing": 72, "dribbling": 80, "defending": 42, "physical": 82, "nationality": "Guinea"}
    ],
    "RB Leipzig": [
        {"name": "Péter Gulácsi", "position": "GK", "rating": 82, "pace": 48, "shooting": 40, "passing": 74, "dribbling": 76, "defending": 46, "physical": 75, "nationality": "Hungría"},
        {"name": "Willi Orbán", "position": "CB", "rating": 83, "pace": 62, "shooting": 48, "passing": 66, "dribbling": 66, "defending": 84, "physical": 84, "nationality": "Hungría"},
        {"name": "Castello Lukeba", "position": "CB", "rating": 80, "pace": 76, "shooting": 40, "passing": 68, "dribbling": 72, "defending": 81, "physical": 80, "nationality": "Francia"},
        {"name": "Lutsharel Geertruida", "position": "RB", "rating": 80, "pace": 78, "shooting": 65, "passing": 75, "dribbling": 76, "defending": 81, "physical": 82, "nationality": "Países Bajos"},
        {"name": "David Raum", "position": "LB", "rating": 81, "pace": 84, "shooting": 65, "passing": 81, "dribbling": 78, "defending": 76, "physical": 79, "nationality": "Alemania"},
        {"name": "Amadou Haidara", "position": "CDM", "rating": 80, "pace": 76, "shooting": 72, "passing": 77, "dribbling": 80, "defending": 78, "physical": 80, "nationality": "Malí"},
        {"name": "Xaver Schlager", "position": "CM", "rating": 81, "pace": 74, "shooting": 74, "passing": 78, "dribbling": 79, "defending": 81, "physical": 83, "nationality": "Austria"},
        {"name": "Xavi Simons", "position": "CAM", "rating": 83, "pace": 84, "shooting": 80, "passing": 82, "dribbling": 86, "defending": 58, "physical": 70, "nationality": "Países Bajos"},
        {"name": "Christoph Baumgartner", "position": "RW", "rating": 79, "pace": 78, "shooting": 78, "passing": 78, "dribbling": 80, "defending": 64, "physical": 75, "nationality": "Austria"},
        {"name": "Antonio Nusa", "position": "LW", "rating": 77, "pace": 88, "shooting": 72, "passing": 74, "dribbling": 83, "defending": 38, "physical": 64, "nationality": "Noruega"},
        {"name": "Benjamin Šeško", "position": "ST", "rating": 81, "pace": 88, "shooting": 82, "passing": 68, "dribbling": 78, "defending": 40, "physical": 80, "nationality": "Eslovenia"}
    ],
    "VfB Stuttgart": [
        {"name": "Alexander Nübel", "position": "GK", "rating": 80, "pace": 50, "shooting": 40, "passing": 76, "dribbling": 78, "defending": 45, "physical": 74, "nationality": "Alemania"},
        {"name": "Jeff Chabot", "position": "CB", "rating": 78, "pace": 64, "shooting": 38, "passing": 62, "dribbling": 62, "defending": 80, "physical": 85, "nationality": "Alemania"},
        {"name": "Dan-Axel Zagadou", "position": "CB", "rating": 78, "pace": 68, "shooting": 44, "passing": 65, "dribbling": 66, "defending": 79, "physical": 84, "nationality": "Francia"},
        {"name": "Josha Vagnoman", "position": "RB", "rating": 76, "pace": 82, "shooting": 60, "passing": 70, "dribbling": 74, "defending": 75, "physical": 78, "nationality": "Alemania"},
        {"name": "Maximilian Mittelstädt", "position": "LB", "rating": 79, "pace": 80, "shooting": 68, "passing": 78, "dribbling": 78, "defending": 76, "physical": 76, "nationality": "Alemania"},
        {"name": "Atakan Karazor", "position": "CDM", "rating": 78, "pace": 66, "shooting": 60, "passing": 75, "dribbling": 74, "defending": 80, "physical": 82, "nationality": "Alemania"},
        {"name": "Angelo Stiller", "position": "CM", "rating": 80, "pace": 68, "shooting": 72, "passing": 82, "dribbling": 80, "defending": 76, "physical": 76, "nationality": "Alemania"},
        {"name": "Enzo Millot", "position": "CAM", "rating": 79, "pace": 78, "shooting": 74, "passing": 80, "dribbling": 82, "defending": 60, "physical": 68, "nationality": "Francia"},
        {"name": "Jamie Leweling", "position": "RW", "rating": 77, "pace": 86, "shooting": 74, "passing": 72, "dribbling": 79, "defending": 48, "physical": 75, "nationality": "Alemania"},
        {"name": "Chris Führich", "position": "LW", "rating": 80, "pace": 84, "shooting": 77, "passing": 78, "dribbling": 83, "defending": 46, "physical": 66, "nationality": "Alemania"},
        {"name": "Deniz Undav", "position": "ST", "rating": 81, "pace": 76, "shooting": 83, "passing": 78, "dribbling": 80, "defending": 45, "physical": 78, "nationality": "Alemania"}
    ],
    "Paris Saint-Germain": [
        {"name": "Gianluigi Donnarumma", "position": "GK", "rating": 89, "pace": 50, "shooting": 45, "passing": 78, "dribbling": 82, "defending": 50, "physical": 82, "nationality": "Italia"},
        {"name": "Marquinhos", "position": "CB", "rating": 87, "pace": 78, "shooting": 56, "passing": 75, "dribbling": 74, "defending": 88, "physical": 80, "nationality": "Brasil"},
        {"name": "Lucas Beraldo", "position": "CB", "rating": 78, "pace": 72, "shooting": 42, "passing": 76, "dribbling": 75, "defending": 79, "physical": 76, "nationality": "Brasil"},
        {"name": "Achraf Hakimi", "position": "RB", "rating": 84, "pace": 92, "shooting": 75, "passing": 80, "dribbling": 82, "defending": 76, "physical": 78, "nationality": "Marruecos"},
        {"name": "Nuno Mendes", "position": "LB", "rating": 83, "pace": 91, "shooting": 66, "passing": 77, "dribbling": 83, "defending": 78, "physical": 76, "nationality": "Portugal"},
        {"name": "Vitinha", "position": "CM", "rating": 85, "pace": 78, "shooting": 76, "passing": 85, "dribbling": 87, "defending": 74, "physical": 72, "nationality": "Portugal"},
        {"name": "Warren Zaïre-Emery", "position": "CM", "rating": 80, "pace": 78, "shooting": 72, "passing": 79, "dribbling": 81, "defending": 76, "physical": 78, "nationality": "Francia"},
        {"name": "Fabián Ruiz", "position": "CM", "rating": 82, "pace": 68, "shooting": 78, "passing": 84, "dribbling": 82, "defending": 74, "physical": 74, "nationality": "España"},
        {"name": "Ousmane Dembélé", "position": "RW", "rating": 86, "pace": 93, "shooting": 78, "passing": 83, "dribbling": 90, "defending": 36, "physical": 62, "nationality": "Francia"},
        {"name": "Bradley Barcola", "position": "LW", "rating": 81, "pace": 90, "shooting": 76, "passing": 77, "dribbling": 84, "defending": 42, "physical": 66, "nationality": "Francia"},
        {"name": "Gonçalo Ramos", "position": "ST", "rating": 81, "pace": 80, "shooting": 82, "passing": 70, "dribbling": 77, "defending": 44, "physical": 80, "nationality": "Portugal"}
    ],
    "AS Mónaco": [
        {"name": "Philipp Köhn", "position": "GK", "rating": 77, "pace": 50, "shooting": 40, "passing": 72, "dribbling": 74, "defending": 44, "physical": 74, "nationality": "Suiza"},
        {"name": "Wilfried Singo", "position": "CB", "rating": 79, "pace": 82, "shooting": 55, "passing": 68, "dribbling": 75, "defending": 79, "physical": 84, "nationality": "Costa de Marfil"},
        {"name": "Thilo Kehrer", "position": "CB", "rating": 78, "pace": 74, "shooting": 48, "passing": 70, "dribbling": 71, "defending": 79, "physical": 78, "nationality": "Alemania"},
        {"name": "Vanderson", "position": "RB", "rating": 78, "pace": 84, "shooting": 68, "passing": 75, "dribbling": 80, "defending": 74, "physical": 72, "nationality": "Brasil"},
        {"name": "Caio Henrique", "position": "LB", "rating": 80, "pace": 78, "shooting": 68, "passing": 82, "dribbling": 81, "defending": 76, "physical": 72, "nationality": "Brasil"},
        {"name": "Denis Zakaria", "position": "CDM", "rating": 81, "pace": 80, "shooting": 68, "passing": 76, "dribbling": 78, "defending": 81, "physical": 85, "nationality": "Suiza"},
        {"name": "Lamine Camara", "position": "CM", "rating": 77, "pace": 76, "shooting": 72, "passing": 78, "dribbling": 78, "defending": 74, "physical": 76, "nationality": "Senegal"},
        {"name": "Aleksandr Golovin", "position": "CAM", "rating": 82, "pace": 78, "shooting": 79, "passing": 84, "dribbling": 84, "defending": 64, "physical": 68, "nationality": "Rusia"},
        {"name": "Maghnes Akliouche", "position": "RW", "rating": 78, "pace": 80, "shooting": 74, "passing": 79, "dribbling": 83, "defending": 46, "physical": 64, "nationality": "Francia"},
        {"name": "Eliesse Ben Seghir", "position": "LW", "rating": 77, "pace": 82, "shooting": 75, "passing": 77, "dribbling": 83, "defending": 42, "physical": 62, "nationality": "Marruecos"},
        {"name": "Breel Embolo", "position": "ST", "rating": 78, "pace": 81, "shooting": 78, "passing": 70, "dribbling": 78, "defending": 42, "physical": 84, "nationality": "Suiza"}
    ],
    "Stade Brestois 29": [
        {"name": "Marco Bizot", "position": "GK", "rating": 79, "pace": 48, "shooting": 40, "passing": 73, "dribbling": 76, "defending": 45, "physical": 75, "nationality": "Países Bajos"},
        {"name": "Brendan Chardonnet", "position": "CB", "rating": 76, "pace": 66, "shooting": 38, "passing": 60, "dribbling": 62, "defending": 78, "physical": 80, "nationality": "Francia"},
        {"name": "Soumaïla Coulibaly", "position": "CB", "rating": 75, "pace": 74, "shooting": 35, "passing": 62, "dribbling": 65, "defending": 76, "physical": 78, "nationality": "Francia"},
        {"name": "Kenny Lala", "position": "RB", "rating": 77, "pace": 76, "shooting": 68, "passing": 76, "dribbling": 76, "defending": 76, "physical": 75, "nationality": "Francia"},
        {"name": "Jordan Amavi", "position": "LB", "rating": 75, "pace": 76, "shooting": 62, "passing": 72, "dribbling": 74, "defending": 74, "physical": 74, "nationality": "Francia"},
        {"name": "Pierre Lees-Melou", "position": "CDM", "rating": 80, "pace": 70, "shooting": 76, "passing": 80, "dribbling": 80, "defending": 79, "physical": 80, "nationality": "Francia"},
        {"name": "Hugo Magnetti", "position": "CM", "rating": 76, "pace": 72, "shooting": 68, "passing": 75, "dribbling": 76, "defending": 75, "physical": 77, "nationality": "Francia"},
        {"name": "Mahdi Camara", "position": "CM", "rating": 77, "pace": 74, "shooting": 72, "passing": 74, "dribbling": 76, "defending": 77, "physical": 81, "nationality": "Francia"},
        {"name": "Romain Del Castillo", "position": "RW", "rating": 78, "pace": 80, "shooting": 76, "passing": 78, "dribbling": 82, "defending": 48, "physical": 65, "nationality": "Francia"},
        {"name": "Abdallah Sima", "position": "LW", "rating": 76, "pace": 84, "shooting": 75, "passing": 68, "dribbling": 76, "defending": 42, "physical": 76, "nationality": "Senegal"},
        {"name": "Ludovic Ajorque", "position": "ST", "rating": 77, "pace": 68, "shooting": 78, "passing": 70, "dribbling": 72, "defending": 42, "physical": 85, "nationality": "Francia"}
    ],
    "LOSC Lille": [
        {"name": "Lucas Chevalier", "position": "GK", "rating": 80, "pace": 52, "shooting": 42, "passing": 76, "dribbling": 80, "defending": 48, "physical": 76, "nationality": "Francia"},
        {"name": "Bafodé Diakité", "position": "CB", "rating": 79, "pace": 78, "shooting": 48, "passing": 68, "dribbling": 72, "defending": 80, "physical": 80, "nationality": "Francia"},
        {"name": "Alexsandro", "position": "CB", "rating": 77, "pace": 68, "shooting": 40, "passing": 64, "dribbling": 65, "defending": 78, "physical": 82, "nationality": "Brasil"},
        {"name": "Thomas Meunier", "position": "RB", "rating": 77, "pace": 72, "shooting": 72, "passing": 75, "dribbling": 75, "defending": 77, "physical": 80, "nationality": "Bélgica"},
        {"name": "Gabriel Gudmundsson", "position": "LB", "rating": 76, "pace": 82, "shooting": 62, "passing": 72, "dribbling": 76, "defending": 74, "physical": 76, "nationality": "Suecia"},
        {"name": "Benjamin André", "position": "CDM", "rating": 80, "pace": 68, "shooting": 68, "passing": 78, "dribbling": 76, "defending": 82, "physical": 82, "nationality": "Francia"},
        {"name": "Angel Gomes", "position": "CM", "rating": 80, "pace": 78, "shooting": 72, "passing": 82, "dribbling": 85, "defending": 64, "physical": 60, "nationality": "Inglaterra"},
        {"name": "Rémy Cabella", "position": "CAM", "rating": 78, "pace": 74, "shooting": 76, "passing": 80, "dribbling": 82, "defending": 54, "physical": 62, "nationality": "Francia"},
        {"name": "Edon Zhegrova", "position": "RW", "rating": 81, "pace": 86, "shooting": 78, "passing": 78, "dribbling": 86, "defending": 40, "physical": 64, "nationality": "Kosovo"},
        {"name": "Osame Sahraoui", "position": "LW", "rating": 76, "pace": 84, "shooting": 68, "passing": 75, "dribbling": 83, "defending": 38, "physical": 58, "nationality": "Marruecos"},
        {"name": "Jonathan David", "position": "ST", "rating": 82, "pace": 84, "shooting": 83, "passing": 74, "dribbling": 80, "defending": 42, "physical": 78, "nationality": "Canadá"}
    ],
    "Olympique de Marsella": [
        {"name": "Gerónimo Rulli", "position": "GK", "rating": 80, "pace": 50, "shooting": 42, "passing": 76, "dribbling": 79, "defending": 48, "physical": 76, "nationality": "Argentina"},
        {"name": "Leonardo Balerdi", "position": "CB", "rating": 80, "pace": 76, "shooting": 44, "passing": 70, "dribbling": 71, "defending": 81, "physical": 81, "nationality": "Argentina"},
        {"name": "Derek Cornelius", "position": "CB", "rating": 76, "pace": 74, "shooting": 38, "passing": 64, "dribbling": 65, "defending": 77, "physical": 82, "nationality": "Canadá"},
        {"name": "Michael Murillo", "position": "RB", "rating": 77, "pace": 80, "shooting": 65, "passing": 73, "dribbling": 75, "defending": 76, "physical": 76, "nationality": "Panamá"},
        {"name": "Quentin Merlin", "position": "LB", "rating": 77, "pace": 78, "shooting": 66, "passing": 78, "dribbling": 78, "defending": 75, "physical": 70, "nationality": "Francia"},
        {"name": "Pierre-Emile Højbjerg", "position": "CDM", "rating": 81, "pace": 68, "shooting": 74, "passing": 80, "dribbling": 78, "defending": 81, "physical": 83, "nationality": "Dinamarca"},
        {"name": "Geoffrey Kondogbia", "position": "CM", "rating": 79, "pace": 68, "shooting": 72, "passing": 76, "dribbling": 77, "defending": 80, "physical": 85, "nationality": "República Centroafricana"},
        {"name": "Amine Harit", "position": "CAM", "rating": 78, "pace": 82, "shooting": 72, "passing": 79, "dribbling": 84, "defending": 54, "physical": 62, "nationality": "Marruecos"},
        {"name": "Mason Greenwood", "position": "RW", "rating": 80, "pace": 83, "shooting": 82, "passing": 77, "dribbling": 81, "defending": 38, "physical": 68, "nationality": "Inglaterra"},
        {"name": "Luis Henrique", "position": "LW", "rating": 76, "pace": 85, "shooting": 72, "passing": 73, "dribbling": 79, "defending": 42, "physical": 70, "nationality": "Brasil"},
        {"name": "Elye Wahi", "position": "ST", "rating": 78, "pace": 87, "shooting": 78, "passing": 68, "dribbling": 80, "defending": 32, "physical": 72, "nationality": "Francia"}
    ]
}
